// User
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING'
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED'
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED'

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED'
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED'

// Job

export const GET_JOB_PENDING = 'GET_JOB_PENDING'
export const GET_JOB_FULFILLED = 'GET_JOB_FULFILLED'
export const GET_JOB_REJECTED = 'GET_JOB_REJECTED'

export const ADD_JOB_PENDING = 'ADD_JOB_PENDING'
export const ADD_JOB_FULFILLED = 'ADD_JOB_FULFILLED'
export const ADD_JOB_REJECTED = 'ADD_JOB_REJECTED'

export const UPDATE_JOB_PENDING = 'UPDATE_JOB_PENDING'
export const UPDATE_JOB_FULFILLED = 'UPDATE_JOB_FULFILLED'
export const UPDATE_JOB_REJECTED = 'UPDATE_JOB_REJECTED'

export const DELETE_JOB_PENDING = 'DELETE_JOB_PENDING'
export const DELETE_JOB_FULFILLED = 'DELETE_JOB_FULFILLED'
export const DELETE_JOB_REJECTED = 'DELETE_JOB_REJECTED'

// Company

export const GET_COMPANY_PENDING = 'GET_COMPANY_PENDING'
export const GET_COMPANY_FULFILLED = 'GET_COMPANY_FULFILLED'
export const GET_COMPANY_REJECTED = 'GET_COMPANY_REJECTED'

export const ADD_COMPANY_PENDING = 'ADD_COMPANY_PENDING'
export const ADD_COMPANY_FULFILLED = 'ADD_COMPANY_FULFILLED'
export const ADD_COMPANY_REJECTED = 'ADD_COMPANY_REJECTED'

export const UPDATE_COMPANY_PENDING = 'UPDATE_COMPANY_PENDING'
export const UPDATE_COMPANY_FULFILLED = 'UPDATE_COMPANY_FULFILLED'
export const UPDATE_COMPANY_REJECTED = 'UPDATE_COMPANY_REJECTED'

export const DELETE_COMPANY_PENDING = 'DELETE_COMPANY_PENDING'
export const DELETE_COMPANY_FULFILLED = 'DELETE_COMPANY_FULFILLED'
export const DELETE_COMPANY_REJECTED = 'DELETE_COMPANY_REJECTED'

// Category

export const GET_CATEGORY_PENDING = 'GET_CATEGORY_PENDING'
export const GET_CATEGORY_FULFILLED = 'GET_CATEGORY_FULFILLED'
export const GET_CATEGORY_REJECTED = 'GET_CATEGORY_REJECTED'

export const ADD_CATEGORY_PENDING = 'ADD_CATEGORY_PENDING'
export const ADD_CATEGORY_FULFILLED = 'ADD_CATEGORY_FULFILLED'
export const ADD_CATEGORY_REJECTED = 'ADD_CATEGORY_REJECTED'

export const UPDATE_CATEGORY_PENDING = 'UPDATE_CATEGORY_PENDING'
export const UPDATE_CATEGORY_FULFILLED = 'UPDATE_CATEGORY_FULFILLED'
export const UPDATE_CATEGORY_REJECTED = 'UPDATE_CATEGORY_REJECTED'

export const DELETE_CATEGORY_PENDING = 'DELETE_CATEGORY_PENDING'
export const DELETE_CATEGORY_FULFILLED = 'DELETE_CATEGORY_FULFILLED'
export const DELETE_CATEGORY_REJECTED = 'DELETE_CATEGORY_REJECTED'

//Details

export const GET_PERSONAL_PENDING = 'GET_PERSONAL_PENDING'
export const GET_PERSONAL_FULFILLED = 'GET_PERSONAL_FULFILLED'
export const GET_PERSONAL_REJECTED = 'GET_PERSONAL_REJECTED'

export const GET_ACADEMICS_PENDING = 'GET_ACADEMICS_PENDING'
export const GET_ACADEMICS_FULFILLED = 'GET_ACADEMICS_FULFILLED'
export const GET_ACADEMICS_REJECTED = 'GET_ACADEMICS_REJECTED'

export const GET_ADDRESS_PENDING = 'GET_ADDRESS_PENDING'
export const GET_ADDRESS_FULFILLED = 'GET_ADDRESS_FULFILLED'
export const GET_ADDRESS_REJECTED = 'GET_ADDRESS_REJECTED'

export const GET_PHD_details_PENDING = 'GET_PHD_PENDING'
export const GET_PHD_details_FULFILLED = 'GET_PHD_FULFILLED'
export const GET_PHD_details_REJECTED = 'GET_PHD_REJECTED'

export const GET_PHD_sup_PENDING = 'GET_PHD_PENDING'
export const GET_PHD_sup_FULFILLED = 'GET_PHD_FULFILLED'
export const GET_PHD_sup_REJECTED = 'GET_PHD_REJECTED'

export const GET_PASTEMPLOYMENT_PENDING = 'GET_PASTEMPLOYMENT_PENDING'
export const GET_PASTEMPLOYMENT_FULFILLED = 'GET_PASTEMPLOYMENT_FULFILLED'
export const GET_PASTEMPLOYMENT_REJECTED = 'GET_PASTEMPLOYMENT_REJECTED'

export const GET_PREEMPLOYMENT_PENDING = 'GET_PREEMPLOYMENT_PENDING'
export const GET_PREEMPLOYMENT_FULFILLED = 'GET_PREEMPLOYMENT_FULFILLED'
export const GET_PREEMPLOYMENT_REJECTED = 'GET_PREEMPLOYMENT_REJECTED'

export const GET_ADMINEXPERIENCE_PENDING = 'GET_ADMINEXPERIENCE_PENDING'
export const GET_ADMINEXPERIENCE_FULFILLED = 'GET_ADMINEXPERIENCE_FULFILLED'
export const GET_ADMINEXPERIENCE_REJECTED = 'GET_ADMINEXPERIENCE_REJECTED'

export const GET_OUTREACHYPROJECTS_PENDING = 'GET_OUTREACHYPROJECTS_PENDING'
export const GET_OUTREACHYPROJECTS_FULFILLED = 'GET_OUTREACHYPROJECTS_FULFILLED'
export const GET_OUTREACHYPROJECTS_REJECTED = 'GET_OUTREACHYPROJECTS_REJECTED'

export const GET_CONSULTANCYPROJECTS_PENDING = 'GET_CONSULTANCYPROJECTS_PENDING'
export const GET_CONSULTANCYPROJECTS_FULFILLED = 'GET_CONSULTANCYPROJECTS_FULFILLED'
export const GET_CONSULTANCYPROJECTS_REJECTED = 'GET_CONSULTANCYPROJECTS_REJECTED'


export const GET_RDPROJECTS_PENDING = 'GET_RDPROJECTS_PENDING'
export const GET_RDPROJECTS_FULFILLED = 'GET_RDPROJECTS_FULFILLED'
export const GET_RDPROJECTS_REJECTED = 'GET_RDPROJECTS_REJECTED'

export const GET_FACULTYMOBILITYPROG_PENDING = 'GET_FACULTYMOBILITYPROG_PENDING'
export const GET_FACULTYMOBILITYPROG_FULFILLED = 'GET_FACULTYMOBILITYPROG_FULFILLED'
export const GET_FACULTYMOBILITYPROG_REJECTED = 'GET_FACULTYMOBILITYPROG_REJECTED'

export const GET_INNOVPRODDEV_PENDING = 'GET_INNOVPRODDEV_PENDING'
export const GET_INNOVPRODDEV_FULFILLED = 'GET_INNOVPRODDEV_FULFILLED'
export const GET_INNOVPRODDEV_REJECTED = 'GET_INNOVPRODDEV_REJECTED'

export const GET_PROFESSIONALBODIES_PENDING = 'GET_PROFESSIONALBODIES_PENDING'
export const GET_PROFESSIONALBODIES_FULFILLED = 'GET_PROFESSIONALBODIES_FULFILLED'
export const GET_PROFESSIONALBODIES_REJECTED = 'GET_PROFESSIONALBODIES_REJECTED'

export const GET_PUBLICATIONS_PENDING = 'GET_PUBLICATIONS_PENDING'
export const GET_PUBLICATIONS_FULFILLED = 'GET_PUBLICATIONS_FULFILLED'
export const GET_PUBLICATIONS_REJECTED = 'GET_PUBLICATIONS_REJECTED'

export const GET_QUALITYRESEARCHPUBLICATIONS_PENDING = 'GET_QUALITYRESEARCHPUBLICATIONS_PENDING'
export const GET_QUALITYRESEARCHPUBLICATIONS_FULFILLED = 'GET_QUALITYRESEARCHPUBLICATIONS_FULFILLED'
export const GET_QUALITYRESEARCHPUBLICATIONS_REJECTED = 'GET_QUALITYRESEARCHPUBLICATIONSREJECTED'

export const GET_PATENT_PENDING = 'GET_PATENT_PENDING'
export const GET_PATENT_FULFILLED = 'GET_PATENT_FULFILLED'
export const GET_PATENT_REJECTED = 'GET_PATENT_REJECTED'

export const GET_REFERENCE_PENDING = 'GET_REFERENCE_PENDING'
export const GET_REFERENCE_FULFILLED = 'GET_REFERENCE_FULFILLED'
export const GET_REFERENCE_REJECTED = 'GET_REFERENCE_REJECTED'

export const GET_SPECIALAWARDS_PENDING = 'GET_SPECIALAWARDS_PENDING'
export const GET_SPECIALAWARDS_FULFILLED = 'GET_SPECIALAWARDS_FULFILLED'
export const GET_SPECIALAWARDS_REJECTED = 'GET_SPECIALAWARDS_REJECTED'

export const GET_HANDWRITTEN_PENDING = 'GET_HANDWRITTEN_PENDING'
export const GET_HANDWRITTEN_FULFILLED = 'GET_HANDWRITTEN_FULFILLED'
export const GET_HANDWRITTEN_REJECTED = 'GET_HANDWRITTEN_REJECTED'

export const GET_OTHERINFO_PENDING = 'GET_OTHERINFO_PENDING'
export const GET_OTHERINFO_FULFILLED = 'GET_OTHERINFO_FULFILLED'
export const GET_OTHERINFO_REJECTED = 'GET_OTHERINFO_REJECTED'

export const GET_UPLOAD_PENDING = 'GET_UPLOAD_PENDING'
export const GET_UPLOAD_FULFILLED = 'GET_UPLOAD_FULFILLED'
export const GET_UPLOAD_REJECTED = 'GET_UPLOAD_REJECTED'

export const GET_DOCUMENTS_PENDING = 'GET_DOCUMENTS_PENDING'
export const GET_DOCUMENTS_FULFILLED = 'GET_DOCUMENTS_FULFILLED'
export const GET_DOCUMENTS_REJECTED = 'GET_DOCUMENTS_REJECTED'

export const GET_STATES_PENDING = 'GET_STATE_PENDING'
export const GET_STATES_FULFILLED = 'GET_STATE_FULFILLED'
export const GET_STATES_REJECTED = 'GET_STATE_REJECTED'

export const GET_DEPT_PENDING = 'GET_DEPT_PENDING'
export const GET_DEPT_FULFILLED = 'GET_DEPT_FULFILLED'
export const GET_DEPT_REJECTED = 'GET_DEPT_REJECTED'

export const GET_APPLICATION_PENDING = 'GET_APPLICATION_PENDING'
export const GET_APPLICATION_FULFILLED = 'GET_APPLICATION_FULFILLED'
export const GET_APPLICATION_REJECTED = 'GET_APPLICATION_REJECTED'


